<a href="https://colab.research.google.com/github/Emanuel2234/clase-2/blob/main/clase_miner%C3%ADa_de_datos_19_03_26_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/1.4.4_superstore.csv")

In [ ]:
pd.options.display.float_format = '{:.6f}'.format
precios = [1000, 2000, 1500, 300, 600, 500, 5000]
precios_series = pd.Series(precios)
print("lista:", precios)
print(precios_series)

lista: [1000, 2000, 1500, 300, 600, 500, 5000]
0    1000
1    2000
2    1500
3     300
4     600
5     500
6    5000
dtype: int64

In [ ]:
diccionario = [
{"cancion": "La Bachata", "artista": "Manuel Turizo", "reproducciones": "269,343"},
{"cancion": "Te Felicito", "artista": "Shakira", "reproducciones": "101,857"},
{"cancion": "Shakira: Bzrp Mussic Sessions, Vol. 53", "artista": "Shakira", "reproduccioes": "101,857"},
{"cancion": "Parcera", "artista": "Pailita", "reproducciones": "159,147"}
]
datos = pd.DataFrame(diccionario)
# cambiamos print por display
display(datos)

,cancion,artista,reproducciones,reproduccioes
0,La Bachata,Manuel Turizo,"269,343",NaN
1,Te Felicito,Shakira,"101,857",NaN
2,"Shakira: Bzrp Mussic Sessions, Vol. 53",Shakira,NaN,"101,857"
3,Parcera,Pailita,"159,147",NaN

In [ ]:
datos_indice = datos.set_index("cancion")
display(datos_indice)

,artista,reproducciones,reproduccioes
cancion,,,
La Bachata,Manuel Turizo,"269,343",NaN
Te Felicito,Shakira,"101,857",NaN
"Shakira: Bzrp Mussic Sessions, Vol. 53",Shakira,NaN,"101,857"
Parcera,Pailita,"159,147",NaN

In [ ]:
data = pd.read_csv("/content/1.4.4_superstore.csv", parse_dates=["Order Date"], index_col="Order Date")
display(data.head())

,Transaction ID,Order ID,Customer ID,Product Name,Sub-Category,Category,Discount,Order Day,Order Month,Order Weekday,Order Year,Quantity,Segment,State,Profit CLP,Sales CLP
Order Date,,,,,,,,,,,,,,,,
2016-11-03,21865-109365-13542,109365,21865,Xerox 22,Paper,Office Supplies,0.000000,3,11,Thursday,2016,3,Consumer,California,7267,15139
2016-10-08,15745-162026-16405,162026,15745,Xerox 1925,Paper,Office Supplies,0.000000,8,10,Saturday,2016,2,Consumer,California,21713,48251
2017-09-16,10090-136448-10461,136448,10090,Logitech 910-002974 M325 Wireless Mouse for We...,Accessories,Technology,0.200000,16,9,Saturday,2017,2,Consumer,Pennsylvania,11210,37368
2015-10-12,16525-142993-23814,142993,16525,"Contico 72""H Heavy-Duty Storage System",Storage,Office Supplies,0.000000,12,10,Monday,2015,2,Consumer,Washington,0,63826
2016-04-19,15280-115819-4927,115819,15280,PowerGen Dual USB Car Charger,Phones,Technology,0.200000,19,4,Tuesday,2016,5,Consumer,California,10114,31119

In [ ]:
display(data.describe())

,Order ID,Customer ID,Discount,Order Day,Order Month,Order Year,Quantity,Profit CLP,Sales CLP
count,9993.000000,9993.000000,9993.000000,9993.000000,9993.000000,9993.000000,9993.000000,9993.000000,9993.000000
mean,134437.893525,16037.562294,0.156188,15.467727,7.810067,2015.722406,3.789753,22319.731112,178997.910838
std,20252.558140,3429.030030,0.206457,8.748441,3.284598,1.123479,2.225149,182438.910151,485376.239720
min,100006.000000,10015.000000,0.000000,1.000000,1.000000,2014.000000,1.000000,-5139733.000000,346.000000
25%,117156.000000,13045.000000,0.000000,8.000000,5.000000,2015.000000,2.000000,1348.000000,13457.000000
50%,133613.000000,16120.000000,0.200000,15.000000,9.000000,2016.000000,3.000000,6753.000000,42426.000000
75%,152072.000000,18985.000000,0.200000,23.000000,11.000000,2017.000000,5.000000,22867.000000,163491.000000
max,169999.000000,21925.000000,0.800000,31.000000,12.000000,2017.000000,14.000000,6541481.000000,17629716.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9993 entries, 2016-11-03 to 2016-10-21
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction ID  9993 non-null   object
 1   Order ID        9993 non-null   int64
 2   Customer ID     9993 non-null   int64
 3   Product Name    9993 non-null   object
 4   Sub-Category    9993 non-null   object
 5   Category        9993 non-null   object
 6   Discount        9993 non-null   float64
 7   Order Day       9993 non-null   int64
 8   Order Month     9993 non-null   int64
 9   Order Weekday   9993 non-null   object
 10  Order Year      9993 non-null   int64
 11  Quantity        9993 non-null   int64
 12  Segment         9993 non-null   object
 13  State           9993 non-null   object
 14  Profit CLP      9993 non-null   int64
 15  Sales CLP       9993 non-null   int64
dtypes: float64(1), int64(8), object(7)
memory usage: 1.3+ MB

In [ ]:
nombre_columnas = data.columns
print(nombre_columnas)

Index(['Transaction ID', 'Order ID', 'Customer ID', 'Product Name',
       'Sub-Category', 'Category', 'Discount', 'Order Day', 'Order Month',
       'Order Weekday', 'Order Year', 'Quantity', 'Segment', 'State',
       'Profit CLP', 'Sales CLP'],
      dtype='object')

In [ ]:
dimensiones = data.shape
print(dimensiones)

(9993, 16)

In [ ]:
product_name = data["Product Name"]
print(product_name)

Order Date
2016-11-03                                             Xerox 22
2016-10-08                                           Xerox 1925
2017-09-16    Logitech 910-002974 M325 Wireless Mouse for We...
2015-10-12               Contico 72"H Heavy-Duty Storage System
2016-04-19                        PowerGen Dual USB Car Charger
                                    ...
2017-09-23    Belkin 8 Outlet SurgeMaster II Gold Surge Prot...
2015-12-10    Hewlett Packard 610 Color Digital Copier / Pri...
2015-01-04    GBC Standard Recycled Report Covers, Clear Pla...
2015-11-19    Hoover Commercial Soft Guard Upright Vacuum An...
2016-10-21                         GBC Personal VeloBind Strips
Name: Product Name, Length: 9993, dtype: object

In [ ]:

cumple_condicion = lambda columna: columna.startswith("Order") or columna.startswith("ORDER") or columna.startswith("order")

comienza_con_order = [columna for columna in nombre_columnas if cumple_condicion(columna)]
print(comienza_con_order)
data_order = data[comienza_con_order]
display(data_order.head())

['Order ID', 'Order Day', 'Order Month', 'Order Weekday', 'Order Year']

            Order ID  Order Day  Order Month Order Weekday  Order Year
Order Date
2016-11-03    109365          3           11      Thursday        2016
2016-10-08    162026          8           10      Saturday        2016
2017-09-16    136448         16            9      Saturday        2017
2015-10-12    142993         12           10        Monday        2015
2016-04-19    115819         19            4       Tuesday        2016

In [ ]:

data_loc = data.loc[:, comienza_con_order]
display(data_loc.head())
data_iloc = data.iloc[:1000, 2:10]

            Order ID  Order Day  Order Month Order Weekday  Order Year
Order Date
2016-11-03    109365          3           11      Thursday        2016
2016-10-08    162026          8           10      Saturday        2016
2017-09-16    136448         16            9      Saturday        2017
2015-10-12    142993         12           10        Monday        2015
2016-04-19    115819         19            4       Tuesday        2016

In [ ]:
data_sin_order = data.drop(columns=comienza_con_order)
display(data_sin_order.head())

,Transaction ID,Customer ID,Product Name,Sub-Category,Category,Discount,Quantity,Segment,State,Profit CLP,Sales CLP
Order Date,,,,,,,,,,,
2016-11-03,21865-109365-13542,21865,Xerox 22,Paper,Office Supplies,0.000000,3,Consumer,California,7267,15139
2016-10-08,15745-162026-16405,15745,Xerox 1925,Paper,Office Supplies,0.000000,2,Consumer,California,21713,48251
2017-09-16,10090-136448-10461,10090,Logitech 910-002974 M325 Wireless Mouse for We...,Accessories,Technology,0.200000,2,Consumer,Pennsylvania,11210,37368
2015-10-12,16525-142993-23814,16525,"Contico 72""H Heavy-Duty Storage System",Storage,Office Supplies,0.000000,2,Consumer,Washington,0,63826
2016-04-19,15280-115819-4927,15280,PowerGen Dual USB Car Charger,Phones,Technology,0.200000,5,Consumer,California,10114,31119

**contiuar en pagina 5**

In [ ]:
data_ordenada = data.sort_index()
print("- Data ordenada:")
display(data_ordenada.head())
print("\n- Selección de filas:")
display(data.loc["2017-07-01"&"2017-07-03"])

- Data ordenada:

,Transaction ID,Order ID,Customer ID,Product Name,Sub-Category,Category,Discount,Order Day,Order Month,Order Weekday,Order Year,Quantity,Segment,State,Profit CLP,Sales CLP
Order Date,,,,,,,,,,,,,,,,
2014-01-03,13000-103800-24285,103800,13000,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Paper,Office Supplies,0.200000,3,1,Friday,2014,2,Consumer,Texas,4323,12809
2014-01-04,19195-112326-2348,112326,19195,Avery 508,Labels,Office Supplies,0.200000,4,1,Saturday,2014,3,Home Office,Illinois,3327,9177
2014-01-04,19195-112326-2354,112326,19195,GBC Standard Plastic Binding Systems Combs,Binders,Office Supplies,0.800000,4,1,Saturday,2014,2,Home Office,Illinois,-4273,2757
2014-01-04,19195-112326-2351,112326,19195,SAFCO Boltless Steel Shelving,Storage,Office Supplies,0.200000,4,1,Saturday,2014,3,Home Office,Illinois,-50443,212393
2014-01-05,18085-141817-5390,141817,18085,Avery Hi-Liter EverBold Pen Style Fluorescent ...,Art,Office Supplies,0.200000,5,1,Sunday,2014,3,Consumer,Pennsylvania,3803,15214

- Selección de filas:

TypeError: unsupported operand type(s) for &: 'str' and 'str'

In [ ]:
print(df[["Sub-Category","Category"]])

     Sub-Category         Category
0           Paper  Office Supplies
1           Paper  Office Supplies
2     Accessories       Technology
3         Storage  Office Supplies
4          Phones       Technology
...           ...              ...
9988   Appliances  Office Supplies
9989      Copiers       Technology
9990      Binders  Office Supplies
9991   Appliances  Office Supplies
9992      Binders  Office Supplies

[9993 rows x 2 columns]

In [ ]:
print(df["Order Date"])

0       2016-11-03
1       2016-10-08
2       2017-09-16
3       2015-10-12
4       2016-04-19
           ...
9988    2017-09-23
9989    2015-12-10
9990    2015-01-04
9991    2015-11-19
9992    2016-10-21
Name: Order Date, Length: 9993, dtype: object

In [ ]:
condicion = data["State"] == "New York"
print(condicion)
data_new_york = data[condicion]
display(data_new_york.head())

Order Date
2016-11-03    False
2016-10-08    False
2017-09-16    False
2015-10-12    False
2016-04-19    False
              ...
2017-09-23    False
2015-12-10     True
2015-01-04    False
2015-11-19    False
2016-10-21    False
Name: State, Length: 9993, dtype: bool

,Transaction ID,Order ID,Customer ID,Product Name,Sub-Category,Category,Discount,Order Day,Order Month,Order Weekday,Order Year,Quantity,Segment,State,Profit CLP,Sales CLP
Order Date,,,,,,,,,,,,,,,,
2015-05-08,18400-160857-16986,160857,18400,DAX Black Cherry Wood-Tone Poster Frame,Furnishings,Furniture,0.000000,8,5,Friday,2015,3,Consumer,New York,23508,61864
2016-02-21,11245-168410-15888,168410,11245,9-3/4 Diameter Round Wall Clock,Furnishings,Furniture,0.000000,21,2,Sunday,2016,5,Corporate,New York,22552,53695
2016-05-07,12010-128818-6714,128818,12010,Bady BDG101FRU Card Printer,Machines,Technology,0.000000,7,5,Saturday,2016,5,Consumer,New York,903339,3114961
2015-12-04,20335-161718-10222,161718,20335,Global Leather Highback Executive Chair with P...,Chairs,Furniture,0.100000,4,12,Friday,2015,2,Consumer,New York,53214,281724
2017-09-20,20365-100111-18197,100111,20365,"TOPS ""Important Message"" Pads, Canary, 4-1/4 x...",Paper,Office Supplies,0.000000,20,9,Wednesday,2017,9,Consumer,New York,14099,29997

In [ ]:
data_new_york_query = data.query("State == 'New York'")

In [ ]:
condicion1 = data["Order Day"] > 25
condicion2 = data["Order Month"] == 12
condicion = condicion1 & condicion2 # &: and
display(data[condicion])

,Transaction ID,Order ID,Customer ID,Product Name,Sub-Category,Category,Discount,Order Day,Order Month,Order Weekday,Order Year,Quantity,Segment,State,Profit CLP,Sales CLP
Order Date,,,,,,,,,,,,,,,,
2015-12-30,12565-135580-17966,135580,12565,2300 Heavy-Duty Transfer File Systems by Perma,Storage,Office Supplies,0.000000,30,12,Wednesday,2015,3,Consumer,California,11088,58360
2016-12-30,14185-160486-27821,160486,14185,Embossed Ink Jet Note Cards,Paper,Office Supplies,0.200000,30,12,Friday,2016,4,Consumer,Florida,19686,56244
2015-12-31,11035-120901-18113,120901,11035,Stockwell Push Pins,Fasteners,Office Supplies,0.200000,31,12,Thursday,2015,2,Consumer,Texas,441,2716
2015-12-28,13960-119697-512,119697,13960,Lenovo 17-Key USB Numeric Keypad,Accessories,Technology,0.200000,28,12,Monday,2015,2,Consumer,Pennsylvania,1059,42352
2014-12-27,15490-106334-13749,106334,15490,Bevis Steel Folding Chairs,Chairs,Furniture,0.200000,27,12,Saturday,2014,3,Consumer,California,17933,179331
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-31,16555-160395-3537,160395,16555,"Crayola Anti Dust Chalk, 12/Pack",Art,Office Supplies,0.000000,31,12,Saturday,2016,2,Corporate,Nevada,1276,2835
2017-12-28,14665-136539-2910,136539,14665,Stanley Bostitch Contemporary Electric Pencil ...,Art,Office Supplies,0.200000,28,12,Thursday,2017,2,Consumer,Texas,2116,21157
2014-12-31,16375-133592-23342,133592,16375,Xerox 1917,Paper,Office Supplies,0.000000,31,12,Wednesday,2014,4,Home Office,Rhode Island,71607,152355
2014-12-31,11815-127383-13759,127383,11815,Staple envelope,Envelopes,Office Supplies,0.200000,31,12,Wednesday,2014,2,Corporate,Texas,13993,38601
2014-12-30,10960-131800-25097,131800,10960,"Cardinal HOLDit! Binder Insert Strips,Extra St...",Binders,Office Supplies,0.200000,30,12,Tuesday,2014,7,Consumer,New York,10007,27605